-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, "%Y-%m-%d") as START_DATE, DATE_FORMAT(END_DATE, "%Y-%m-%d") as END_DATE, 
CASE 
    WHEN DATE_FORMAT(END_DATE, "%m") = "09" and DATE_FORMAT(END_DATE, "%d") - DATE_FORMAT(START_DATE, "%d") + 1 < 30 then "단기 대여" 
    WHEN DATE_FORMAT(END_DATE, "%m") = "10" and DATE_FORMAT(END_DATE, "%d") - DATE_FORMAT(START_DATE, "%d") + 1 < 0 then "단기 대여" 
    ELSE "장기 대여"
END as RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE like "2022-09%"
ORDER BY HISTORY_ID DESC